using System;
using System.Linq;

namespace VYaml.SourceGenerator;

// Pure, symbol-free emitter: builds the generated source from an equatable TypeMetaModel.
// Because it only reads value data, it lives behind the model in the pipeline and is skipped
// (along with the model) whenever an edit leaves the model unchanged.
static class IncrementalEmitter
{
    public static string Emit(TypeMetaModel model)
    {
        var codeWriter = new CodeWriter();

        codeWriter.AppendLine("// <auto-generated />");
        codeWriter.AppendLine("#nullable enable");
        codeWriter.AppendLine("#pragma warning disable CS0162 // Unreachable code");
        codeWriter.AppendLine("#pragma warning disable CS0219 // Variable assigned but never used");
        codeWriter.AppendLine("#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.");
        codeWriter.AppendLine("#pragma warning disable CS8601 // Possible null reference assignment");
        codeWriter.AppendLine("#pragma warning disable CS8602 // Possible null return");
        codeWriter.AppendLine("#pragma warning disable CS8604 // Possible null reference argument for parameter");
        codeWriter.AppendLine("#pragma warning disable CS8619 // Possible null reference assignment fix");
        codeWriter.AppendLine("#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method");
        codeWriter.AppendLine();
        codeWriter.AppendLine("using System;");
        codeWriter.AppendLine("using VYaml.Annotations;");
        codeWriter.AppendLine("using VYaml.Parser;");
        codeWriter.AppendLine("using VYaml.Emitter;");
        codeWriter.AppendLine("using VYaml.Serialization;");
        codeWriter.AppendLine();

        if (model.HasNamespace)
        {
            codeWriter.AppendLine($"namespace {model.Namespace}");
            codeWriter.BeginBlock();
        }

        using (codeWriter.BeginBlockScope($"partial {model.TypeDeclarationKeyword} {model.TypeName}"))
        {
            if (!model.IsInterface)
            {
                EmitRegisterMethod(model, codeWriter);
            }
            EmitFormatter(model, codeWriter);
        }

        if (model.HasNamespace)
        {
            codeWriter.EndBlock();
        }

        codeWriter.AppendLine("#pragma warning restore CS0162 // Unreachable code");
        codeWriter.AppendLine("#pragma warning restore CS0219 // Variable assigned but never used");
        codeWriter.AppendLine("#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.");
        codeWriter.AppendLine("#pragma warning restore CS8601 // Possible null reference assignment");
        codeWriter.AppendLine("#pragma warning restore CS8602 // Possible null return");
        codeWriter.AppendLine("#pragma warning restore CS8604 // Possible null reference argument for parameter");
        codeWriter.AppendLine("#pragma warning restore CS8631 // The type cannot be used as type parameter in the generic type or method");

        return codeWriter.ToString();
    }

    static void EmitRegisterMethod(TypeMetaModel model, CodeWriter codeWriter)
    {
        codeWriter.AppendLine("[VYaml.Annotations.Preserve]");
        var modifier = model.HasBaseYamlObject ? "public static new" : "public static";
        using var _ = codeWriter.BeginBlockScope($"{modifier} void __RegisterVYamlFormatter()");
        codeWriter.AppendLine($"global::VYaml.Serialization.GeneratedResolver.Register(new {model.SanitizedTypeName}GeneratedFormatter());");
    }

    static void EmitFormatter(TypeMetaModel model, CodeWriter codeWriter)
    {
        var returnType = ReturnType(model);

        codeWriter.AppendLine("[VYaml.Annotations.Preserve]");
        using var _ = codeWriter.BeginBlockScope($"public class {model.SanitizedTypeName}GeneratedFormatter : IYamlFormatter<{returnType}>");

        if (model.IsUnion)
        {
            EmitSerializeMethodUnion(model, codeWriter);
            EmitDeserializeMethodUnion(model, codeWriter);
            return;
        }

        foreach (var member in model.Members)
        {
            codeWriter.Append($"static readonly byte[] {member.Name}KeyUtf8Bytes = ");
            codeWriter.AppendByteArrayString(member.KeyNameUtf8Bytes);
            codeWriter.AppendLine($"; // {member.KeyName}", false);
            codeWriter.AppendLine();
        }

        EmitSerializeMethod(model, codeWriter);
        EmitDeserializeMethod(model, codeWriter);
    }

    static void EmitSerializeMethod(TypeMetaModel model, CodeWriter codeWriter)
    {
        var returnType = ReturnType(model);

        codeWriter.AppendLine("[VYaml.Annotations.Preserve]");
        using var methodScope = codeWriter.BeginBlockScope(
            $"public void Serialize(ref Utf8YamlEmitter emitter, {returnType} value, YamlSerializationContext context)");

        if (!model.IsValueType)
        {
            using (codeWriter.BeginBlockScope("if (value is null)"))
            {
                codeWriter.AppendLine("emitter.WriteNull();");
                codeWriter.AppendLine("return;");
            }
        }

        codeWriter.AppendLine("emitter.BeginMapping();");
        foreach (var member in model.Members)
        {
            var ignoreScope = EmitIgnoreConditionCheck(codeWriter, member);

            if (member.HasKeyNameAlias || model.NamingConventionByType != NamingConvention.LowerCamelCase)
            {
                codeWriter.AppendLine($"emitter.WriteString(\"{member.KeyName}\");");
            }
            else
            {
                using (codeWriter.BeginBlockScope($"if (context.Options.NamingConvention == global::VYaml.Annotations.NamingConvention.{member.NamingConventionByType})"))
                {
                    codeWriter.AppendLine($"emitter.WriteScalar({member.Name}KeyUtf8Bytes);");
                }
                using (codeWriter.BeginBlockScope("else"))
                {
                    codeWriter.AppendLine($"global::VYaml.Serialization.NamingConventionMutator.MutateToThreadStaticBufferUtf8({member.Name}KeyUtf8Bytes, context.Options.NamingConvention, out var mutated, out var written);");
                    codeWriter.AppendLine("emitter.WriteScalar(mutated.AsSpan(0, written));");
                }
            }
            codeWriter.AppendLine($"context.Serialize(ref emitter, value.{member.Name});");

            if (ignoreScope != null)
            {
                ignoreScope.Dispose();
                codeWriter.AppendLine("}");
            }
        }
        codeWriter.AppendLine("emitter.EndMapping();");
    }

    static IDisposable? EmitIgnoreConditionCheck(CodeWriter codeWriter, MemberMetaModel member)
    {
        if (member.IsReferenceType || member.IsNullableValueType)
        {
            codeWriter.AppendLine(
                $"if (context.Options.DefaultIgnoreCondition == global::VYaml.Serialization.YamlIgnoreCondition.Never || " +
                $"value.{member.Name} != null)");
            codeWriter.AppendLine("{");
            return codeWriter.BeginIndentScope();
        }

        if (member.IsValueType)
        {
            codeWriter.AppendLine(
                $"if (context.Options.DefaultIgnoreCondition != global::VYaml.Serialization.YamlIgnoreCondition.WhenWritingDefault || " +
                $"{member.DefaultValueComparison})");
            codeWriter.AppendLine("{");
            return codeWriter.BeginIndentScope();
        }

        return null;
    }

    static void EmitSerializeMethodUnion(TypeMetaModel model, CodeWriter codeWriter)
    {
        var returnType = ReturnType(model);

        codeWriter.AppendLine("[VYaml.Annotations.Preserve]");
        using var methodScope = codeWriter.BeginBlockScope(
            $"public void Serialize(ref Utf8YamlEmitter emitter, {returnType} value, YamlSerializationContext context)");

        if (!model.IsValueType)
        {
            using (codeWriter.BeginBlockScope("if (value is null)"))
            {
                codeWriter.AppendLine("emitter.WriteNull();");
                codeWriter.AppendLine("return;");
            }
        }

        using (codeWriter.BeginBlockScope("switch (value)"))
        {
            foreach (var union in model.Unions)
            {
                codeWriter.AppendLine($"case {union.FullTypeName} x:");
                codeWriter.AppendLine($"    emitter.Tag(\"{union.SubTypeTag}\");");
                codeWriter.AppendLine($"    context.Serialize(ref emitter, x);");
                codeWriter.AppendLine( "    break;");
            }
        }
    }

    static void EmitDeserializeMethod(TypeMetaModel model, CodeWriter codeWriter)
    {
        var returnType = ReturnType(model);
        codeWriter.AppendLine("[VYaml.Annotations.Preserve]");
        using var methodScope = codeWriter.BeginBlockScope(
            $"public {returnType} Deserialize(ref YamlParser parser, YamlDeserializationContext context)");

        using (codeWriter.BeginBlockScope("if (parser.IsNullScalar())"))
        {
            codeWriter.AppendLine("parser.Read();");
            codeWriter.AppendLine("return default;");
        }

        if (model.Members.Count <= 0)
        {
            codeWriter.AppendLine("parser.SkipCurrentNode();");
            codeWriter.AppendLine($"return new {model.TypeName}();");
            return;
        }

        codeWriter.AppendLine("parser.ReadWithVerify(ParseEventType.MappingStart);");
        codeWriter.AppendLine();
        foreach (var member in model.Members)
        {
            codeWriter.AppendLine($"var __{member.Name}__ = {member.DefaultValueExpression};");
        }

        using (codeWriter.BeginBlockScope("while (!parser.End && parser.CurrentEventType != ParseEventType.MappingEnd)"))
        {
            using (codeWriter.BeginBlockScope("if (parser.CurrentEventType != ParseEventType.Scalar)"))
            {
                codeWriter.AppendLine("throw new YamlSerializerException(parser.CurrentMark, \"Custom type deserialization supports only string key\");");
            }
            codeWriter.AppendLine();
            using (codeWriter.BeginBlockScope("if (!parser.TryGetScalarAsSpan(out var key))"))
            {
                codeWriter.AppendLine("throw new YamlSerializerException(parser.CurrentMark, \"Custom type deserialization supports only string key\");");
            }
            codeWriter.AppendLine();

            using (codeWriter.BeginBlockScope($"if (context.Options.NamingConvention != global::VYaml.Annotations.NamingConvention.{model.NamingConventionByType})"))
            {
                codeWriter.AppendLine($"global::VYaml.Serialization.NamingConventionMutator.MutateToThreadStaticBufferUtf8(key, global::VYaml.Annotations.NamingConvention.{model.NamingConventionByType}, out var mutated, out var written);");
                codeWriter.AppendLine("key = mutated.AsSpan(0, written);");
            }

            using (codeWriter.BeginBlockScope("switch (key.Length)"))
            {
                var membersByNameLength = model.Members.GroupBy(x => x.KeyNameUtf8Bytes.Length);
                foreach (var group in membersByNameLength)
                {
                    using (codeWriter.BeginIndentScope($"case {group.Key}:"))
                    {
                        var branching = "if";
                        foreach (var member in group)
                        {
                            using (codeWriter.BeginBlockScope($"{branching} (key.SequenceEqual({member.Name}KeyUtf8Bytes))"))
                            {
                                codeWriter.AppendLine("parser.Read(); // skip key");
                                codeWriter.AppendLine($"__{member.Name}__ = context.DeserializeWithAlias<{member.FullTypeName}>(ref parser);");
                                codeWriter.AppendLine("continue;");
                            }
                            branching = "else if";
                        }
                        codeWriter.AppendLine("goto default;");
                    }
                }

                using (codeWriter.BeginIndentScope("default:"))
                {
                    codeWriter.AppendLine("parser.Read(); // skip key");
                    codeWriter.AppendLine("parser.SkipCurrentNode(); // skip value");
                    codeWriter.AppendLine("continue;");
                }
            }
        }
        codeWriter.AppendLine("parser.ReadWithVerify(ParseEventType.MappingEnd);");

        codeWriter.Append("return new ");
        if (model.HasConstructor)
        {
            var parameters = string.Join(",", model.ConstructorParameterNames.Select(x => $"__{x}__"));
            codeWriter.Append($"{model.TypeName}({parameters})", false);
        }
        else
        {
            codeWriter.Append($"{model.TypeName}", false);
        }

        if (model.SetterMemberNames.Count > 0)
        {
            using (codeWriter.BeginBlockScope())
            {
                foreach (var setterName in model.SetterMemberNames)
                {
                    codeWriter.AppendLine($"{setterName} = __{setterName}__,");
                }
            }
        }
        codeWriter.AppendLine(";");
    }

    static void EmitDeserializeMethodUnion(TypeMetaModel model, CodeWriter codeWriter)
    {
        var returnType = ReturnType(model);

        codeWriter.AppendLine("[VYaml.Annotations.Preserve]");
        using var methodScope = codeWriter.BeginBlockScope(
            $"public {returnType} Deserialize(ref YamlParser parser, YamlDeserializationContext context)");

        using (codeWriter.BeginBlockScope("if (parser.IsNullScalar())"))
        {
            codeWriter.AppendLine("parser.Read();");
            codeWriter.AppendLine("return default;");
        }

        using (codeWriter.BeginBlockScope("if (!parser.TryGetCurrentTag(out var tag))"))
        {
            codeWriter.AppendLine("throw new YamlSerializerException(parser.CurrentMark, \"Cannot find any tag for union\");");
        }

        codeWriter.AppendLine();

        var branch = "if";
        foreach (var union in model.Unions)
        {
            using (codeWriter.BeginBlockScope($"{branch} (tag.Equals(\"{union.SubTypeTag}\")) "))
            {
                codeWriter.AppendLine($"return context.DeserializeWithAlias<{union.FullTypeName}>(ref parser);");
            }
            branch = "else if";
        }
        using (codeWriter.BeginBlockScope("else"))
        {
            codeWriter.AppendLine("throw new YamlSerializerException(parser.CurrentMark, \"Cannot find any subtype tag for union\");");
        }
    }

    static string ReturnType(TypeMetaModel model) =>
        model.IsValueType ? model.FullTypeName : $"{model.FullTypeName}?";
}
